php:
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS="--prefer-stable"

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  apt:
    update: true
    packages:
      - acl

install:
  - composer self-update 1.10.15
  - composer update --no-interaction --prefer-dist $COMPOSER_FLAGS

script:
  - vendor/bin/grumphp run
